### ISSUE TITLE
the commands are not working and idk why

### ISSUE THREAD

**Issue by achocolatemilk** [yogurtsyum/in-game-ranking#10]

**Comment by IeuanGol** [comment]
Is bot online? Is there any errors? Do you have a `.env` file?

Please provide more information.

Thank you

**Comment by achocolatemilk** [comment]
> Is bot online? Is there any errors? Do you have a `.env` file?
> 
> Please provide more information.
> 
> Thank you
yes i have a .env file and I cant find any errors. I dont know how to see if its online or make the bot online

**Comment by IeuanGol** [comment]
Sorry my fault, didn't notice this is IGR. 

Is there anything in your studio logs `/console` or F9 button?

**Comment by achocolatemilk** [comment]
> Sorry my fault, didn't notice this is IGR.
> 
> Is there anything in your studio logs `/console` or F9 button?

i know your gonna think im dumb but where do I do /console or F9

**Comment by achocolatemilk** [comment]
> Sorry my fault, didn't notice this is IGR.
> 
> Is there anything in your studio logs `/console` or F9 button?

I saw that HTTP requests were off so I turned it on does that help?

**Comment by IeuanGol** [comment]
> > Sorry my fault, didn't notice this is IGR.
> > 
> > Is there anything in your studio logs `/console` or F9 button?
> 
> i know your gonna think im dumb but where do I do /console or F9

In game

**Comment by IeuanGol** [comment]
> > Sorry my fault, didn't notice this is IGR.
> > 
> > Is there anything in your studio logs `/console` or F9 button?
> 
> I saw that HTTP requests were off so I turned it on does that help?

Yes this needs to be enabled

**Comment by achocolatemilk** [comment]
> > > Sorry my fault, didn't notice this is IGR.
> > > Is there anything in your studio logs `/console` or F9 button?
> > 
> > 
> > I saw that HTTP requests were off so I turned it on does that help?
> 
> Yes this needs to be enabled

ok i enabled it but they still dont work

**Comment by IeuanGol** [comment]
What does the console now display?

**Comment by achocolatemilk** [comment]
> What does the console now display?
let me see

**Comment by achocolatemilk** [comment]
> What does the console now display?

do you have discord? it would be easier to talk there

**Comment by IeuanGol** [comment]
Currently the support server is locked sorry.

**Comment by achocolatemilk** [comment]
> What does the console now display?

ok so what am I looking for

**Comment by IeuanGol** [comment]
> > > Sorry my fault, didn't notice this is IGR.
> > > 
> > > Is there anything in your studio logs `/console` or F9 button?
> > 
> > i know your gonna think im dumb but where do I do /console or F9
> 
> In game

**Comment by achocolatemilk** [comment]
> > > > Sorry my fault, didn't notice this is IGR.
> > > > Is there anything in your studio logs `/console` or F9 button?
> > > 
> > > 
> > > i know your gonna think im dumb but where do I do /console or F9
> > 
> > 
> > In game



> What does the console now display?

so there is too much to type out is there anything specific i need to show you?

**Comment by IeuanGol** [comment]
A screenshot should be sufficient.

**Comment by achocolatemilk** [comment]
> A screenshot should be sufficient.

![Screenshot (235)](https://user-images.githubusercontent.com/69214466/92731792-86e90d00-f343-11ea-9d7d-60acb5d2073c.png)
![Screenshot (236)](https://user-images.githubusercontent.com/69214466/92731811-8d778480-f343-11ea-86e4-4a0cffc8ed88.png)
![Screenshot (237)](https://user-images.githubusercontent.com/69214466/92731825-92d4cf00-f343-11ea-936b-64aa7b35a47b.png)

**Comment by achocolatemilk** [comment]
![Screenshot (241)](https://user-images.githubusercontent.com/69214466/92731853-a08a5480-f343-11ea-8954-565463b9ec16.png)

**Comment by IeuanGol** [comment]
None of these errors is related to igr.

**Comment by achocolatemilk** [comment]
> None of these errors is related to igr.

Thats all that was there

**Comment by achocolatemilk** [comment]
> None of these errors is related to igr.

is there anything else to show you?

**Comment by nihonjin0619** [comment]
Try .env It might work

**Comment by emergingdarkness** [comment]
What about .env??

**Comment by TheShadowGamer** [comment]
Sorry for the late response. You can join the [support server for help](https://discord.gg/Wv3nUNj6Av)
