### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Maxii-ui** [yogurtsyum/in-game-ranking#11]
![err](https://user-images.githubusercontent.com/63369269/92414593-3a3fdf00-f155-11ea-9443-4ae71cc905b9.PNG)

**Comment by IeuanGol** [comment]
`npm i express`

**Comment by Maxii-ui** [comment]
Now, I have that error in studio.
![dba759c64e98c80922ee70150c139203](https://user-images.githubusercontent.com/63369269/92415541-b0dedb80-f159-11ea-9a4d-ad9403d5861b.png)
![ERR2](https://user-images.githubusercontent.com/63369269/92415542-b4726280-f159-11ea-9cee-9af9f317ee2b.PNG)

**Comment by Maxii-ui** [comment]
@IeuanGol can u help me? ;/

**Comment by IeuanGol** [comment]
What happens when you access the link directly? (in the browser)

**Comment by yogurtsyum** [comment]
Can you show the web server logs?

**Comment by Maxii-ui** [comment]
It's says OK,
![e3719011d12574cf7dcbf1e988594488](https://user-images.githubusercontent.com/63369269/92416898-ec7ca400-f15f-11ea-9fa5-5d3c3888de85.png)

**Comment by Maxii-ui** [comment]
@yogurtsyum ^^

**Comment by Maxii-ui** [comment]
https://user-images.githubusercontent.com/63369269/92415542-b4726280-f159-11ea-9cee-9af9f317ee2b.PNG

**Comment by IeuanGol** [comment]
is http requests enabled?

**Comment by Maxii-ui** [comment]
Yeah

**Comment by Maxii-ui** [comment]
welp no one is gonna help me

**Comment by IeuanGol** [comment]
Enable http requests.

**Comment by TheShadowGamer** [comment]
Do you have a group ID in your .env?

**Comment by TheShadowGamer** [comment]
(Sorry for the late response. You can also join the [support server for help](https://discord.gg/Wv3nUNj6Av))
