### ISSUE TITLE
Problem / Url Error Report.

### ISSUE THREAD

**Issue by intorsetorpolice1intorsetoprolice** [yogurtsyum/in-game-ranking#12]
This doesnt work, they helped me in NO FUCKING WAY. I want help. Thanks.

**Comment by BillyH-0167** [comment]
why are u being a cunt, and making it a huge issue, 

First off: You havnt gave an error so how do u expect us to know the issue

Second; Go to the support server first

**Comment by intorsetorpolice1intorsetoprolice** [comment]
First: i did they didnt help me

Second: FUCK YOU.

**Comment by BillyH-0167** [comment]
We are trying to help you , so theres no need to be rude, The support server is ran by the community, so we dont reply instantly. And as i said you havnt gave an error.

**Comment by intorsetorpolice1intorsetoprolice** [comment]
I WAS GIVEN NO ERROR, ITS JUST THIS. 
![image](https://user-images.githubusercontent.com/59117519/120104882-97018080-c14e-11eb-944b-3c84b47d7bae.png)
So yeh!

**Comment by intorsetorpolice1intorsetoprolice** [comment]
I WAS GIVEN NO ERROR, ITS JUST THIS. 
![image](https://user-images.githubusercontent.com/59117519/120104882-97018080-c14e-11eb-944b-3c84b47d7bae.png)
So yeh!

**Comment by BillyH-0167** [comment]
There is an error there, Its says "HTTP URL INVALID"
![image](https://user-images.githubusercontent.com/48413205/120104925-bbf5f380-c14e-11eb-9ac5-3cf22503d4ea.png)

**Comment by BillyH-0167** [comment]
So update it to ur correct url...

**Comment by intorsetorpolice1intorsetoprolice** [comment]
WHAT IS THE CORRECT URL??!!!

**Comment by intorsetorpolice1intorsetoprolice** [comment]
still get that eather way 
![image](https://user-images.githubusercontent.com/59117519/120105680-e9906c00-c151-11eb-9014-d70a46d31625.png)

**Comment by intorsetorpolice1intorsetoprolice** [comment]
Anyone who can help please, do I am now calm.

**Comment by BillyH-0167** [comment]
YOu get the URL from the host you are using,

**Comment by intorsetorpolice1intorsetoprolice** [comment]
i am using the same host but i am comfused what i actually put in the thingy.

**Comment by intorsetorpolice1intorsetoprolice** [comment]
can u show me what it should look like in the script?

**Comment by intorsetorpolice1intorsetoprolice** [comment]
Please.

**Comment by intorsetorpolice1intorsetoprolice** [comment]
Soemtime today.

**Comment by BrightZebrafish** [comment]
be patient, not everyones lives are about discord and roblox they will reply when they are free

**Comment by intorsetorpolice1intorsetoprolice** [comment]
Ok.

**Comment by BillyH-0167** [comment]
How do you expect us to know ur hosts project name?

**Comment by intorsetorpolice1intorsetoprolice** [comment]
ask me

**Comment by intorsetorpolice1intorsetoprolice** [comment]
https://SomeDimgraySeptagon.kieranflanagan.repl.co

**Comment by intorsetorpolice1intorsetoprolice** [comment]
[here](https://SomeDimgraySeptagon.kieranflanagan.repl.co)

**Comment by BillyH-0167** [comment]
And is that the one you have in ur script

**Comment by intorsetorpolice1intorsetoprolice** [comment]
Yes sir.

**Comment by yogurtsyum** [comment]
Please stop spamming us on GitHub for help, and remember that my open source projects are free, and everyone helping you is a community volunteer.

When you spam us us on GitHub and Discord and be rude to us, it just makes no one want to help you.

Everything you're asking about here is covered in the setup guide. Please read that thoroughly before creating an issue: https://github.com/yogurtsyum/in-game-ranking/wiki/setup

And if you still need help after reading it, then you can either come back here and ask a specific question (not "it's not working") or ask in the support server.

**Comment by intorsetorpolice1intorsetoprolice** [comment]
Ok! I am having this error, please can you support me with it: 

![image](https://user-images.githubusercontent.com/59117519/120113966-d6db5e80-c174-11eb-8190-39822a8e7b71.png)


And here is my host link: https://somedimgrayseptagon.kieranflanagan.repl.co

Get back to me when you can thanks!

**Comment by yogurtsyum** [comment]
Please send a screenshot of the line in the Lua Script where you put the host link.

**Comment by intorsetorpolice1intorsetoprolice** [comment]
Ok! https://gyazo.com/7de2824959e54d559572ac331b114534
![image](https://user-images.githubusercontent.com/59117519/120115538-0772c680-c17c-11eb-942c-f97ba165be44.png)

**Comment by BillyH-0167** [comment]
Ur missing a `/` at the end

**Comment by intorsetorpolice1intorsetoprolice** [comment]
Thanks it wokin now.
