### ISSUE TITLE
Major security issue

### ISSUE THREAD

**Issue by BillyH-0167** [yogurtsyum/in-game-ranking#13]
After replying to a few issues in the support server, it seems like there is a major security issue, GET requests are no good when doing actions such as setRank. promote, etc, Id suggest upgrading to POST requests and using headers instead of queries, The issue with GET requests are anyone can mask them with the querys, Meanwhile with POST you can use headers so that would block most browser requests on google chrome, Which is a better way, POST Requests should be used since you can use headers which is a better security measure than a GET request.

**Comment by yogurtsyum** [comment]
Hello BillyH-0167,

This has been fixed in the latest version by switching to POST requests, and our users will be recommended to update to this version. 

Thank you again for helping us find this bug.
