### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by Iovelove** [yogurtsyum/in-game-ranking#19]
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

how do you fix this?
the code is from index.js from YOUR in-game-ranking NOTHING MODIFIED

![image](https://user-images.githubusercontent.com/48948872/131670690-1bf305ec-e434-4022-ae34-1422c6e210ce.png)

**Comment by InceptionStrange** [comment]
Hello, if you need support You should join in the Discord: https://discord.gg/rgABazHp97, Some staff members will be ready to help you!

**Comment by yogurtsyum** [comment]
As @InceptionStrange said, please use the support server before opening an issue if you just have a simple error like this. Thanks.
